export const SEO_KEYWORDS = {
  en: {
    home: [
      "Innovatek SWD",
      "AI operational software UAE",
      "Arabic-ready business software",
      "donation management software",
      "facility management software",
      "visitor management system",
      "AI customer communication platform",
      "Dubai software company",
    ],
    solutions: [
      "operational software solutions UAE",
      "donation management platform",
      "CMMS software UAE",
      "facilities maintenance software",
      "visitor management software",
      "AI communication platform",
      "Arabic-ready software",
      "Innovatek SWD",
    ],
    about: [
      "Innovatek SWD",
      "UAE software company",
      "Dubai software company",
      "Arabic software development",
      "operational software product team",
      "enterprise software integration UAE",
      "AI software company UAE",
    ],
    contact: [
      "Innovatek SWD contact",
      "book software consultation Dubai",
      "operational software working session",
      "AI software consultation UAE",
      "donation software demo",
      "facility management software demo",
      "visitor management system demo",
      "Innovatek SWD sales",
    ],
    privacy: [
      "Innovatek SWD privacy notice",
      "website privacy policy UAE",
      "Innovatek data privacy",
    ],
    terms: [
      "Innovatek SWD website terms",
      "website terms of use UAE",
      "Innovatek terms and conditions",
    ],
  },
  ar: {
    home: [
      "إنوفاتك SWD",
      "برمجيات تشغيلية ذكية في الإمارات",
      "برمجيات أعمال عربية",
      "برنامج إدارة التبرعات",
      "برنامج إدارة المرافق",
      "نظام إدارة الزوار",
      "منصة تواصل ذكية مع العملاء",
      "شركة برمجيات في دبي",
    ],
    solutions: [
      "حلول البرمجيات التشغيلية",
      "برنامج إدارة التبرعات",
      "نظام إدارة صيانة المرافق",
      "برنامج CMMS في الإمارات",
      "نظام إدارة الزوار",
      "منصة تواصل ذكية",
      "برمجيات أعمال عربية",
      "إنوفاتك SWD",
    ],
    about: [
      "إنوفاتك SWD",
      "شركة برمجيات في الإمارات",
      "شركة برمجيات في دبي",
      "تطوير برمجيات عربية",
      "فريق منتجات برمجية",
      "تكامل الأنظمة في الإمارات",
      "شركة ذكاء اصطناعي في الإمارات",
    ],
    contact: [
      "التواصل مع إنوفاتك SWD",
      "حجز استشارة برمجيات في دبي",
      "جلسة عمل للبرمجيات التشغيلية",
      "استشارة ذكاء اصطناعي في الإمارات",
      "عرض برنامج إدارة التبرعات",
      "عرض برنامج إدارة المرافق",
      "عرض نظام إدارة الزوار",
      "مبيعات إنوفاتك",
    ],
    privacy: [
      "إشعار خصوصية إنوفاتك SWD",
      "سياسة خصوصية الموقع في الإمارات",
      "خصوصية البيانات في إنوفاتك",
    ],
    terms: [
      "شروط موقع إنوفاتك SWD",
      "شروط استخدام الموقع في الإمارات",
      "أحكام وشروط إنوفاتك",
    ],
  },
};

export const SOLUTION_KEYWORDS = {
  en: {
    "donation-hub": [
      "Donation Hub",
      "donation management software UAE",
      "charity donation platform",
      "fundraising management software",
      "donation kiosk software",
      "digital donation platform",
      "donation reconciliation software",
      "foundation management software",
    ],
    "bunyan-cmms": [
      "Bunyan CMMS",
      "Twin AI",
      "CMMS software UAE",
      "facility management software",
      "maintenance management system",
      "asset management software",
      "work order management",
      "facilities maintenance platform",
    ],
    "visitor-management-system": [
      "Smart VMS",
      "visitor management system UAE",
      "visitor registration software",
      "contractor management system",
      "reception management software",
      "access control visitor management",
      "host notification system",
      "secure visitor check-in",
    ],
    "communication-platform": [
      "Communication Platform",
      "AI customer communication platform",
      "omnichannel customer service UAE",
      "unified inbox software",
      "customer engagement platform",
      "AI customer support software",
      "email messaging workflow",
      "customer request management",
    ],
  },
  ar: {
    "donation-hub": [
      "Donation Hub",
      "برنامج إدارة التبرعات في الإمارات",
      "منصة تبرعات للجمعيات الخيرية",
      "برنامج إدارة جمع التبرعات",
      "برنامج أكشاك التبرع",
      "منصة تبرعات رقمية",
      "برنامج مطابقة التبرعات",
      "برنامج إدارة المؤسسات الخيرية",
    ],
    "bunyan-cmms": [
      "بنيان CMMS",
      "Twin AI",
      "برنامج CMMS في الإمارات",
      "برنامج إدارة المرافق",
      "نظام إدارة الصيانة",
      "برنامج إدارة الأصول",
      "إدارة أوامر العمل",
      "منصة صيانة المرافق",
    ],
    "visitor-management-system": [
      "Smart VMS",
      "نظام إدارة الزوار في الإمارات",
      "برنامج تسجيل الزوار",
      "نظام إدارة المقاولين",
      "برنامج إدارة الاستقبال",
      "إدارة الزوار والتحكم بالدخول",
      "نظام إشعارات المضيف",
      "تسجيل دخول الزوار الآمن",
    ],
    "communication-platform": [
      "منصة التواصل",
      "منصة تواصل ذكية مع العملاء",
      "خدمة عملاء متعددة القنوات في الإمارات",
      "برنامج صندوق وارد موحد",
      "منصة تفاعل العملاء",
      "برنامج دعم العملاء بالذكاء الاصطناعي",
      "مسارات البريد والمراسلة",
      "إدارة طلبات العملاء",
    ],
  },
};

type SolutionLocale = keyof typeof SOLUTION_KEYWORDS;

export function getSolutionKeywords(locale: SolutionLocale, slug: string): string[] {
  const keywords = SOLUTION_KEYWORDS[locale] as Record<string, string[]>;
  return keywords[slug] ?? SEO_KEYWORDS[locale].solutions;
}
